#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "fider"
name = "Fider"
description.en = "Open platform to collect and prioritize feedback"
description.fr = "Plateforme ouverte pour récolter et prioriser les retours utilisateurs"

version = "0.29.0~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "AGPL-3.0"
website = "https://fider.io"
demo = "https://feedback.fider.io"
admindoc = "https://fider.io/docs"
code = "https://github.com/getfider/fider"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "1200M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "Fider should be public for external people to vote."
    help.fr = "Fider doit être public pour que des personnes externes votent."
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "fr"]
    default = "en"

    [install.admin]
    type = "user"

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://github.com/getfider/fider/archive/refs/tags/v0.29.0.tar.gz"
    sha256 = "c7454afe82e07a867b89c7b937334e0a102ec62596e0325be614c6d8e268e8ae"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = [
        "g++",
        "postgresql"
    ]

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"

    [resources.go]
    version = "1.22.0"
