#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.25049c93a85256995f9e6c11b4ad73366a5149f7.name = "Upgrade from 0.36.1~ynh1"
