#!/usr/bin/env bash

cd "__INSTALL_DIR__/app"

# Public Host Name
export BASE_URL=https://__DOMAIN____PATH__
export PORT=__PORT__

# Connection string to the PostgreSQL database
export DATABASE_URL="postgres://__DB_USER__:__DB_PWD__@localhost:5432/__DB_NAME__?sslmode=disable"

# Generate a 512-bit secret
export JWT_SECRET=__SECRET__

# From which account e-mails will be sent
export EMAIL_NOREPLY=__APP__@__DOMAIN__

###
# EMAIL
###

export EMAIL_SMTP_HOST=__DOMAIN__
export EMAIL_SMTP_PORT=587
export EMAIL_SMTP_ENABLE_STARTTLS='true'
export EMAIL_SMTP_USERNAME=__APP__
export EMAIL_SMTP_PASSWORD=__MAIL_PWD__

# This file is provided to the administrator to customize OAuth etc.
if [[ -f "custom_fider_env" ]]; then
    source custom_fider_env
fi

./fider migrate
./fider "$@"
